import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from "next/image";
import { IoLogoFacebook, IoLogoGithub, IoLogoTwitter, IoLogoGoogle } from 'react-icons/io5'
const Login = () => {
    const route = useRouter();
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-image absolute inset-0">
                <div className="bg-black h-full opacity-70"> </div>
                <div className="shape-1 absolute left-0 right-0 bottom-0"></div>
            </div>
            <div className="flex z-10 relative flex-col justify-center items-center   h-screen">
                <div className="border bg-white rounded-md p-6 lg:w-4/12  w-10/12 md:w-8/12">
                    <Image alt="" src={'/assets/img-1.png'} height={'100'} width={'100'} className={'mx-auto'} />
                    <p className="font-bold text-center text-lg text-cyan-900 mt-2">Belma</p>
                    <p className="text-center text-sm text-gray-500">Create New Account</p>
                    <form action="" onSubmit={(e) => { e.preventDefault(); route.push('/dashboard') }} method="post" className="my-10 flex flex-col gap-5">
                        <div >
                            <label htmlFor="" className="font-medium block">Username</label>
                            <input type="text" placeholder="Enter username" className="block border rounded-md w-full py-3 px-3 text-sm mt-2 focus:border-red-500" />
                        </div>
                        <div>
                            <label htmlFor="" className="font-medium block">Password</label>
                            <input type="password" placeholder="Enter password" className="block border rounded-md w-full py-3 px-3 text-sm mt-2" />
                            <Link href={'/forgot_password'} className={'text-right  block my-3 text-gray-600 hover:underline hover:text-blue-500'}>Forgot Password</Link>
                        </div>
                        <div>
                            <input type="checkbox" name="Remember me" id="checkbox" className="mr-2" />
                            <label htmlFor="checkbox">Remember Me</label>
                        </div>
                        <button type="submit" className="bg-green-700 hover:bg-green-600 text-white w-full font-semibold rounded-md p-3">Login</button>
                    </form>
                    <div className="flex items-center">
                        <hr className="bg-gray-500   flex-1  " />
                        <p className="px-4 text-cyan-900">OR</p>
                        <hr className="bg-gray-500   flex-1  " />
                    </div>
                    <p className="text-center my-4">Sign in with</p>
                    <div className="flex items-center justify-center gap-4">
                        <button className="bg-blue-800 rounded-sm p-2 flex items-center justify-center  text-white w-10 h-10">
                            <IoLogoFacebook className="text-3xl" />
                        </button>
                        <button className="bg-red-800 rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoGoogle className="text-3xl" />
                        </button>
                        <button className="bg-black rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoGithub className="text-3xl" />
                        </button>
                        <button className="bg-blue-500 rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoTwitter className="text-3xl" />
                        </button>
                    </div>
                </div>
                <p className="my-4">Don&apos;t have an account ? <Link href={"/signup"} className={'underline text-blue-500'}> Signup</Link></p>
            </div>
        </>
    )
}

export default Login;