import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router"; 
const Logout = () => {
     
    return (
        <>
            <Head>
                <title>Logout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-image absolute inset-0">
                <div className="bg-black h-full opacity-80"> d</div>
                <div className="shape-1 absolute left-0 right-0 bottom-0">d</div>
            </div>
            <div className="flex z-10 relative flex-col justify-center items-center   h-screen">
                <div className="border bg-white rounded-md p-6 lg:w-4/12  w-10/12 md:w-8/12">
                    <p className="font-bold text-center text-lg text-cyan-800">You are Logged Out</p>
                    <p className="text-center text-sm text-gray-500">Thank you for using Belma</p>
                    <Link href={"/login"} className={'bg-green-700 font-semibold my-4 text-center  p-2 text-white w-full rounded-md block'}> Login</Link>
                </div>

            </div>
        </>
    )
}

export default Logout;