import Head from "next/head";
import Link from "next/link";
import { IoLogoFacebook, IoLogoGithub, IoLogoTwitter, IoLogoGoogle } from 'react-icons/io5'
const Login = () => {

    return (
        <>
            <Head>
                <title>Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-image absolute inset-0">
                <div className="bg-black h-full opacity-80"> d</div>
                <div className="shape-1 absolute left-0 right-0 bottom-0">d</div>
            </div>
            <div className="flex z-10 relative flex-col justify-center items-center   h-screen">
                <div className="border bg-white rounded-md p-6 lg:w-4/12  w-10/12 md:w-8/12">
                    <p className="font-bold text-center text-lg text-cyan-800">Create New Account</p>
                    <p className="text-center text-sm text-gray-500">Get your free Belma account now</p>
                    <form action="" method="post" className="my-10 flex flex-col gap-5">
                        <div >
                            <label htmlFor="" className="font-semibold block">Email</label>
                            <input type="text" placeholder="Enter email address" className="block border rounded-sm w-full py-2 px-3 text-sm mt-2 focus:border-red-500" />
                        </div>
                        <div >
                            <label htmlFor="" className="font-semibold block">Username</label>
                            <input type="text" placeholder="Enter username" className="block border rounded-sm w-full py-2 px-3 text-sm mt-2 focus:border-red-500" />
                        </div>
                        <div>
                            <label htmlFor="" className="font-semibold block">Password</label>
                            <input type="password" placeholder="Enter password" className="block border rounded-sm w-full py-2 px-3 text-sm mt-2" />
                        </div>
                         <p className="italic text-gray-400 text-sm">By registering you agree to the Belma <Link href={'#'} className={'underline text-blue-500'}>Terms of Use</Link></p>
                        <button type="submit" className="bg-green-700 text-white w-full font-semibold rounded-sm p-2">Sign Up</button>
                    </form>
                    <p className="text-center my-4">Create account with</p>
                    <div className="flex items-center justify-center gap-1">
                        <button className="bg-blue-800 rounded-sm p-2 flex items-center justify-center  text-white w-10 h-10">
                            <IoLogoFacebook className="text-3xl" />
                        </button>
                        <button className="bg-red-800 rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoGoogle className="text-3xl" />
                        </button>
                        <button className="bg-black rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoGithub className="text-3xl" />
                        </button>
                        <button className="bg-blue-500 rounded-sm p-2 flex items-center justify-center text-white w-10 h-10">
                            <IoLogoTwitter className="text-3xl" />
                        </button>
                    </div>
                </div>
                <p className="my-4">Already have an account ? <Link href={"/login"} className={'underline text-blue-500'}> Login</Link></p>
            </div>
        </>
    )
}

export default Login;